# docs: https://github.com/sasstools/sass-lint
# rules: https://github.com/sasstools/sass-lint/tree/master/docs/rules
# Get the default of this file which will contain any new rules: https://github.com/sasstools/sass-lint/blob/master/docs/sass-lint.yml

# Log levels
# 0 = Disabled
# 1 = Warning
# 2 = Error

files:
  include: 'scss/**/*.scss'
  ignore:
    - 'scss/00-config/_icons.scss'
    - 'scss/60-pages/_styleguide-specific.scss'
options:
  formatter: 'stylish'
  merge-default-rules: false
rules:
  attribute-quotes:
    - 2
    -
      include: true
  bem-depth:
    - 2
    -
      max-depth: 1
  border-zero:
    - 2
    -
      convention: '0'
  brace-style:
    - 2
    -
      style: '1tbs'
      allow-single-line: false
  class-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedbem
      ignore: []
  clean-import-paths:
    - 2
    -
      filename-extension: false
      leading-underscore: false
  empty-args:
    - 2
    -
      include: true
  empty-line-between-blocks:
    - 2
    -
      include: true
      allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 2
    -
      include: true
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'snakecase'
  hex-length:
    - 2
    -
      style: 'short'
  hex-notation:
    - 2
    -
      style: 'lowercase'
  id-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
      ignore: []
  indentation:
    - 2
    -
      size: 2
  leading-zero:
    - 2
    -
      include: true
  mixin-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  mixins-before-declarations:
    - 2
    -
      exclude: ['breakpoint', 'card-context']
  nesting-depth:
    - 2
    -
      max-depth: 4
  no-attribute-selectors: 0
  no-color-keywords: 2
  no-color-literals:
    - 2
    -
      allow-map-identifiers: false
      allow-rgba: true
      allow-variable-identifiers: false
  no-combinators: 0
  no-css-comments: 2
  no-debug: 0
  no-duplicate-properties:
    - 2
    - 
      exclude:
        - 'src'
  no-empty-rulesets: 2
  no-extends: 2
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 2
    -
      allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: false
  no-transition-all: 2
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-universal-selectors: 0
  no-url-protocols: 2
  no-vendor-prefixes:
    - 2
    -
      excluded-identifiers: []
  no-warn: 0
  one-declaration-per-line: 2
  placeholder-in-extend: 2
  placeholder-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  property-sort-order:
    - 0
    -
      order: 'alphabetical'
  pseudo-element: 0
  quotes:
    - 2
    -
      style: 'double'
  single-line-per-selector: 2
  space-after-bang:
    - 2
    -
      include: false
  space-after-colon:
    - 2
    -
      include: true
  space-after-comma:
    - 2
    -
      include: true
  space-around-operator:
    - 2
    -
      include: true
  space-before-bang:
    - 2
    -
      include: true
  space-before-brace:
    - 2
    -
      include: true
  space-before-colon:
    - 2
    -
      include: false
  space-between-parens:
    - 2
    -
      include: false
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedbem'
  zero-unit:
    - 2
    -
      include: false
